# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlicksApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlicksApp

  target 'FlicksAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlicksAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
